/*
Copyright 2025 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: resource_manager_client.go

// Package resource_manager_client is a generated GoMock package.
package resource_manager_client

import (
	"context"
	"reflect"

	"github.com/golang/mock/gomock"
	"github.com/vllm-project/aibrix/apps/console/api/resource_manager/provider/tce/resource_manager_client/scheduled_plan_types"
	"github.com/vllm-project/aibrix/apps/console/api/resource_manager/provider/tce/resource_manager_client/supply_domain_types"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CancelScheduledMatch mocks base method.
func (m *MockClient) CancelScheduledMatch(ctx context.Context, id string) (*scheduled_plan_types.MatchingResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelScheduledMatch", ctx, id)
	ret0, _ := ret[0].(*scheduled_plan_types.MatchingResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelScheduledMatch indicates an expected call of CancelScheduledMatch.
func (mr *MockClientMockRecorder) CancelScheduledMatch(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelScheduledMatch", reflect.TypeOf((*MockClient)(nil).CancelScheduledMatch), ctx, id)
}

// CommitScheduledMatch mocks base method.
func (m *MockClient) CommitScheduledMatch(ctx context.Context, id string) (*scheduled_plan_types.MatchingResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitScheduledMatch", ctx, id)
	ret0, _ := ret[0].(*scheduled_plan_types.MatchingResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitScheduledMatch indicates an expected call of CommitScheduledMatch.
func (mr *MockClientMockRecorder) CommitScheduledMatch(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitScheduledMatch", reflect.TypeOf((*MockClient)(nil).CommitScheduledMatch), ctx, id)
}

// CreateScheduledMatch mocks base method.
func (m *MockClient) CreateScheduledMatch(ctx context.Context, query *scheduled_plan_types.MatchingIntentRequest) (*scheduled_plan_types.MatchingResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScheduledMatch", ctx, query)
	ret0, _ := ret[0].(*scheduled_plan_types.MatchingResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateScheduledMatch indicates an expected call of CreateScheduledMatch.
func (mr *MockClientMockRecorder) CreateScheduledMatch(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScheduledMatch", reflect.TypeOf((*MockClient)(nil).CreateScheduledMatch), ctx, query)
}

// GetQuotaView mocks base method.
func (m *MockClient) GetQuotaView(ctx context.Context, req *scheduled_plan_types.QuotaViewReq) ([]*scheduled_plan_types.QuotaViewItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuotaView", ctx, req)
	ret0, _ := ret[0].([]*scheduled_plan_types.QuotaViewItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuotaView indicates an expected call of GetQuotaView.
func (mr *MockClientMockRecorder) GetQuotaView(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuotaView", reflect.TypeOf((*MockClient)(nil).GetQuotaView), ctx, req)
}

// GetScheduledMatch mocks base method.
func (m *MockClient) GetScheduledMatch(ctx context.Context, id string) (*scheduled_plan_types.MatchingResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduledMatch", ctx, id)
	ret0, _ := ret[0].(*scheduled_plan_types.MatchingResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduledMatch indicates an expected call of GetScheduledMatch.
func (mr *MockClientMockRecorder) GetScheduledMatch(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduledMatch", reflect.TypeOf((*MockClient)(nil).GetScheduledMatch), ctx, id)
}

// GetScheduledMatchDetail mocks base method.
func (m *MockClient) GetScheduledMatchDetail(ctx context.Context, id string) (*scheduled_plan_types.MatchingDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduledMatchDetail", ctx, id)
	ret0, _ := ret[0].(*scheduled_plan_types.MatchingDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduledMatchDetail indicates an expected call of GetScheduledMatchDetail.
func (mr *MockClientMockRecorder) GetScheduledMatchDetail(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduledMatchDetail", reflect.TypeOf((*MockClient)(nil).GetScheduledMatchDetail), ctx, id)
}

// GetStatistics mocks base method.
func (m *MockClient) GetStatistics(ctx context.Context, query *scheduled_plan_types.ListMatchQuery) (*scheduled_plan_types.GetStatisticsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatistics", ctx, query)
	ret0, _ := ret[0].(*scheduled_plan_types.GetStatisticsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatistics indicates an expected call of GetStatistics.
func (mr *MockClientMockRecorder) GetStatistics(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatistics", reflect.TypeOf((*MockClient)(nil).GetStatistics), ctx, query)
}

// GetMatchTimeline mocks base method.
func (m *MockClient) GetMatchTimeline(ctx context.Context, matchID string) ([]scheduled_plan_types.MatchTimelineEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMatchTimeline", ctx, matchID)
	ret0, _ := ret[0].([]scheduled_plan_types.MatchTimelineEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMatchTimeline indicates an expected call of GetMatchTimeline.
func (mr *MockClientMockRecorder) GetMatchTimeline(ctx, matchID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMatchTimeline", reflect.TypeOf((*MockClient)(nil).GetMatchTimeline), ctx, matchID)
}

// GetSupplyDomains mocks base method.
func (m *MockClient) GetSupplyDomains(ctx context.Context, req *supply_domain_types.GetSupplyDomainsRequest) ([]*supply_domain_types.SupplyDomainResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupplyDomains", ctx, req)
	ret0, _ := ret[0].([]*supply_domain_types.SupplyDomainResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSupplyDomains indicates an expected call of GetSupplyDomains.
func (mr *MockClientMockRecorder) GetSupplyDomains(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupplyDomains", reflect.TypeOf((*MockClient)(nil).GetSupplyDomains), ctx, req)
}

// ListFilterOptions mocks base method.
func (m *MockClient) ListFilterOptions(ctx context.Context) (*scheduled_plan_types.ListFilterOptionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFilterOptions", ctx)
	ret0, _ := ret[0].(*scheduled_plan_types.ListFilterOptionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFilterOptions indicates an expected call of ListFilterOptions.
func (mr *MockClientMockRecorder) ListFilterOptions(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFilterOptions", reflect.TypeOf((*MockClient)(nil).ListFilterOptions), ctx)
}

// ListScheduledMatch mocks base method.
func (m *MockClient) ListScheduledMatch(ctx context.Context, query *scheduled_plan_types.ListMatchQuery) (*scheduled_plan_types.ListMatchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScheduledMatch", ctx, query)
	ret0, _ := ret[0].(*scheduled_plan_types.ListMatchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListScheduledMatch indicates an expected call of ListScheduledMatch.
func (mr *MockClientMockRecorder) ListScheduledMatch(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScheduledMatch", reflect.TypeOf((*MockClient)(nil).ListScheduledMatch), ctx, query)
}

// UpdateScheduledMatch mocks base method.
func (m *MockClient) UpdateScheduledMatch(ctx context.Context, id string, query *scheduled_plan_types.MatchingIntentRequest) (*scheduled_plan_types.MatchingResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScheduledMatch", ctx, id, query)
	ret0, _ := ret[0].(*scheduled_plan_types.MatchingResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateScheduledMatch indicates an expected call of UpdateScheduledMatch.
func (mr *MockClientMockRecorder) UpdateScheduledMatch(ctx, id, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScheduledMatch", reflect.TypeOf((*MockClient)(nil).UpdateScheduledMatch), ctx, id, query)
}
