/*
Copyright 2025 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: bytequota_client.go

// Package bytequota_client is a generated GoMock package.
package bytequota_client

import (
	"context"
	"reflect"

	"github.com/golang/mock/gomock"
	"github.com/vllm-project/aibrix/apps/console/api/resource_manager/provider/tce/bytequota_client/resource_pool_types"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetBusinessLineInfo mocks base method.
func (m *MockClient) GetBusinessLineInfo(ctx context.Context, psm, platform string) (*BusinessLineInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBusinessLineInfo", ctx, psm, platform)
	ret0, _ := ret[0].(*BusinessLineInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBusinessLineInfo indicates an expected call of GetBusinessLineInfo.
func (mr *MockClientMockRecorder) GetBusinessLineInfo(ctx, psm, platform interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBusinessLineInfo", reflect.TypeOf((*MockClient)(nil).GetBusinessLineInfo), ctx, psm, platform)
}

// GetBusinessLineInfoV2 mocks base method.
func (m *MockClient) GetBusinessLineInfoV2(ctx context.Context, psm string) (*BusinessLineInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBusinessLineInfoV2", ctx, psm)
	ret0, _ := ret[0].(*BusinessLineInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBusinessLineInfoV2 indicates an expected call of GetBusinessLineInfoV2.
func (mr *MockClientMockRecorder) GetBusinessLineInfoV2(ctx, psm interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBusinessLineInfoV2", reflect.TypeOf((*MockClient)(nil).GetBusinessLineInfoV2), ctx, psm)
}

// ListResourcePools mocks base method.
func (m *MockClient) ListResourcePools(ctx context.Context, query *resource_pool_types.ListResourcePoolsRequest) ([]*resource_pool_types.ResourcePoolResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResourcePools", ctx, query)
	ret0, _ := ret[0].([]*resource_pool_types.ResourcePoolResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResourcePools indicates an expected call of ListResourcePools.
func (mr *MockClientMockRecorder) ListResourcePools(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResourcePools", reflect.TypeOf((*MockClient)(nil).ListResourcePools), ctx, query)
}
