/*
Copyright 2025 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: parser.go
//
// Generated by this command:
//
//	mockgen -source=parser.go -destination=./parser_mock.go -package=json
//
// Package json is a generated GoMock package.
package json

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockParser is a mock of Parser interface.
type MockParser struct {
	ctrl     *gomock.Controller
	recorder *MockParserMockRecorder
}

// MockParserMockRecorder is the mock recorder for MockParser.
type MockParserMockRecorder struct {
	mock *MockParser
}

// NewMockParser creates a new mock instance.
func NewMockParser(ctrl *gomock.Controller) *MockParser {
	mock := &MockParser{ctrl: ctrl}
	mock.recorder = &MockParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParser) EXPECT() *MockParserMockRecorder {
	return m.recorder
}

// Marshal mocks base method.
func (m *MockParser) Marshal(v any) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Marshal", v)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Marshal indicates an expected call of Marshal.
func (mr *MockParserMockRecorder) Marshal(v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Marshal", reflect.TypeOf((*MockParser)(nil).Marshal), v)
}

// MarshalToString mocks base method.
func (m *MockParser) MarshalToString(v any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarshalToString", v)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarshalToString indicates an expected call of MarshalToString.
func (mr *MockParserMockRecorder) MarshalToString(v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarshalToString", reflect.TypeOf((*MockParser)(nil).MarshalToString), v)
}

// Unmarshal mocks base method.
func (m *MockParser) Unmarshal(data []byte, v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unmarshal", data, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unmarshal indicates an expected call of Unmarshal.
func (mr *MockParserMockRecorder) Unmarshal(data, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmarshal", reflect.TypeOf((*MockParser)(nil).Unmarshal), data, v)
}

// UnmarshalFromString mocks base method.
func (m *MockParser) UnmarshalFromString(str string, v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalFromString", str, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmarshalFromString indicates an expected call of UnmarshalFromString.
func (mr *MockParserMockRecorder) UnmarshalFromString(str, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalFromString", reflect.TypeOf((*MockParser)(nil).UnmarshalFromString), str, v)
}
